services:
  issueapi:
    build: .
    restart: unless-stopped
    volumes:
      - ./instance:/opt/issueapi/instance
    expose:
      - "8000"
    depends_on:
      - auxiliary_service
    environment:
      - RANKING_SERVICE_HOST=auxiliary_service

  auxiliary_service:
    build:
      context: .
      dockerfile: auxiliary_service/Dockerfile
    restart: unless-stopped
    expose:
      - "50051"

  client:
    build: ./issueapi-client
    restart: unless-stopped
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - issueapi
      - client

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"