server {
    listen 80 default_server;
    server_name _;
    return 444; # Drop the connection
}

upstream app_server {
    server issueapi:8000;
}

upstream client_server {
    server client:80;
}

server {
    listen 80;
    server_name projects.issueapi.viljoholma.fi; # Hostname, change if deployed elsewhere

    # Required for Let's Encrypt certificate validation (ACME Challenge)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # This redirect will send all Port 80 traffic to HTTPS.
    location / {
         return 301 https://$host$request_uri;
    }
}

# PRODUCTION CONFIGURATION (Port 443)
# These blocks require valid SSL certificates in ./certbot/conf/live/

server {
    listen 443 ssl default_server;
    server_name _;
    
    ssl_certificate /etc/letsencrypt/live/projects.issueapi.viljoholma.fi/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/projects.issueapi.viljoholma.fi/privkey.pem;
    
    return 444;
}

server {
    listen 443 ssl;
    server_name projects.issueapi.viljoholma.fi;

    keepalive_timeout 5;

    ssl_certificate /etc/letsencrypt/live/projects.issueapi.viljoholma.fi/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/projects.issueapi.viljoholma.fi/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    location /api/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://app_server;
    }

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://client_server;
    }
}
