server {
    listen 80 default_server;
    server_name _;
    return 444; # Drop the connection
}

upstream app_server {
    server issueapi:8000;
}

server {
    listen 80;
    server_name projects.issueapi.viljoholma.fi;

    # Required for Let's Encrypt certificate validation (ACME Challenge)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # IMPORTANT: Keep this commented out until you have successfully 
    # generated your first SSL certificate with Certbot.
    location / {
         return 301 https://$host$request_uri;
    }
}

# IMPORTANT: Keep all below that commented out until certificates exist 
# in the ./certbot/conf/live/projects.issueapi.viljoholma.fi/ directory.

server {
    listen 443 ssl default_server;
    server_name _;
    
    ssl_certificate /etc/letsencrypt/live/projects.issueapi.viljoholma.fi/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/projects.issueapi.viljoholma.fi/privkey.pem;
    
    return 444;
}

server {
    listen 443 ssl;
    server_name projects.issueapi.viljoholma.fi;

    keepalive_timeout 5;

    ssl_certificate /etc/letsencrypt/live/projects.issueapi.viljoholma.fi/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/projects.issueapi.viljoholma.fi/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        
        proxy_pass http://app_server;
    }
}
